//
// Generated file, do not edit! Created by opp_msgc 4.2 from src/node/communication/routing/aodvTestRouting/AodvTestRoutingDataPacket.msg.
//

#ifndef _AODVTESTROUTINGDATAPACKET_M_H_
#define _AODVTESTROUTINGDATAPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Class generated from <tt>src/node/communication/routing/aodvTestRouting/AodvTestRoutingDataPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet PacketDATA extends RoutingPacket 
 * {
 * 	string destinationAodv;
 * }
 * </pre>
 */
class PacketDATA : public ::RoutingPacket
{
  protected:
    opp_string destinationAodv_var;

  private:
    void copy(const PacketDATA& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketDATA&);

  public:
    PacketDATA(const char *name=NULL, int kind=0);
    PacketDATA(const PacketDATA& other);
    virtual ~PacketDATA();
    PacketDATA& operator=(const PacketDATA& other);
    virtual PacketDATA *dup() const {return new PacketDATA(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestinationAodv() const;
    virtual void setDestinationAodv(const char * destinationAodv);
};

inline void doPacking(cCommBuffer *b, PacketDATA& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PacketDATA& obj) {obj.parsimUnpack(b);}


#endif // _AODVTESTROUTINGDATAPACKET_M_H_
